# fly.toml app configuration file generated for kluster-host on 2023-11-26T23:34:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kluster-host"
primary_region = "ams"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
ASPNETCORE_ENVIRONMENT = "Production"